*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 18:32:14 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:3031 fd 3
probably another instance of uWSGI is running on the same address (localhost:3031).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 18:37:26 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on localhost:3031 fd 3
probably another instance of uWSGI is running on the same address (localhost:3031).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 19:05:39 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address localhost:3031 fd 3
Python version: 3.6.5 (default, May 11 2018, 13:30:17)  [GCC 7.3.0]
Python main interpreter initialized at 0x5603df2556d0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031110 bytes (1006 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
failed to open python file /django5_test/wsgi.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 15276)
spawned uWSGI worker 1 (pid: 15277, cores: 2)
spawned uWSGI worker 2 (pid: 15278, cores: 2)
spawned uWSGI worker 3 (pid: 15279, cores: 2)
spawned uWSGI worker 4 (pid: 15280, cores: 2)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 15277)...
Gracefully killing worker 2 (pid: 15278)...
Gracefully killing worker 3 (pid: 15279)...
Gracefully killing worker 4 (pid: 15280)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /media/aiker/python/mypython/django/django5_test
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (localhost:3031)
running /home/aiker/.virtualenvs/vdjango/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 19:07:04 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address localhost:3031 fd 3
Python version: 3.6.5 (default, May 11 2018, 13:30:17)  [GCC 7.3.0]
Python main interpreter initialized at 0x55eaffeae510
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031110 bytes (1006 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
failed to open python file /django5_test/wsgi.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 15276)
spawned uWSGI worker 1 (pid: 15354, cores: 2)
spawned uWSGI worker 2 (pid: 15355, cores: 2)
spawned uWSGI worker 3 (pid: 15356, cores: 2)
spawned uWSGI worker 4 (pid: 15357, cores: 2)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 15354)...
Gracefully killing worker 2 (pid: 15355)...
Gracefully killing worker 4 (pid: 15357)...
Gracefully killing worker 3 (pid: 15356)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /media/aiker/python/mypython/django/django5_test
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (localhost:3031)
running /home/aiker/.virtualenvs/vdjango/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 19:09:39 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (localhost:3031).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 19:17:44 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
Python version: 3.6.5 (default, May 11 2018, 13:30:17)  [GCC 7.3.0]
Python main interpreter initialized at 0x55e4ced82ee0
python threads support enabled
The -s/--socket option is missing and stdin is not a socket.
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 19:22:54 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
bind(): Permission denied [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 20:31:07 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address localhost:3031 fd 3
Python version: 3.6.5 (default, May 11 2018, 13:30:17)  [GCC 7.3.0]
Python main interpreter initialized at 0x55626afa85c0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031110 bytes (1006 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
failed to open python file /django5_test/
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 26618)
spawned uWSGI worker 1 (pid: 26619, cores: 2)
spawned uWSGI worker 2 (pid: 26620, cores: 2)
spawned uWSGI worker 3 (pid: 26621, cores: 2)
spawned uWSGI worker 4 (pid: 26622, cores: 2)
...gracefully killing workers...
Gracefully killing worker 1 (pid: 26619)...
Gracefully killing worker 3 (pid: 26621)...
Gracefully killing worker 4 (pid: 26622)...
Gracefully killing worker 2 (pid: 26620)...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /media/aiker/python/mypython/django/django5_test
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (localhost:3031)
running /home/aiker/.virtualenvs/vdjango/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 20:31:27 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address localhost:3031 fd 3
Python version: 3.6.5 (default, May 11 2018, 13:30:17)  [GCC 7.3.0]
Python main interpreter initialized at 0x562bf54a0400
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031110 bytes (1006 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
failed to open python file /django5_test/
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 26618)
spawned uWSGI worker 1 (pid: 26636, cores: 2)
spawned uWSGI worker 2 (pid: 26637, cores: 2)
spawned uWSGI worker 3 (pid: 26638, cores: 2)
spawned uWSGI worker 4 (pid: 26639, cores: 2)
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 20:33:08 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (localhost:3031).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 20:35:29 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django/
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (localhost:3031).
bind(): Address already in use [core/socket.c line 769]
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 20:36:19 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
writing pidfile to uwsgi.pid
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (localhost:3031).
bind(): Address already in use [core/socket.c line 769]
...brutally killing workers...
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
binary reloading uWSGI...
chdir() to /media/aiker/python/mypython/django/django5_test
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (localhost:3031)
running /home/aiker/.virtualenvs/vdjango/bin/uwsgi
[uWSGI] getting INI configuration from uwsgi.ini
*** Starting uWSGI 2.0.18 (64bit) on [Mon Aug  5 23:47:41 2019] ***
compiled with version: 7.3.0 on 05 August 2019 09:11:06
os: Linux-4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018
nodename: aiker-PC
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 4
current working directory: /media/aiker/python/mypython/django/django5_test
detected binary path: /home/aiker/.virtualenvs/vdjango/bin/uwsgi
chdir() to /media/aiker/python/mypython/django
your processes number limit is 14936
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address localhost:3031 fd 3
Python version: 3.6.5 (default, May 11 2018, 13:30:17)  [GCC 7.3.0]
Python main interpreter initialized at 0x5654b0b7e400
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1031110 bytes (1006 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
failed to open python file /django5_test
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 26618)
spawned uWSGI worker 1 (pid: 19696, cores: 2)
spawned uWSGI worker 2 (pid: 19697, cores: 2)
spawned uWSGI worker 3 (pid: 19698, cores: 2)
spawned uWSGI worker 4 (pid: 19699, cores: 2)
